package command

import (
	"math/rand"
	"regexp"

	"github.com/elias19r/twitterbot/internal/config"
	"github.com/elias19r/twitterbot/internal/twitter"
)

var inspirationalRegexp = regexp.MustCompile(`(?i)(^|[[:space:]]+)/(inspirational|motivacional)([[:space:]]+|$)`)
var inspirationalInfo = `
/motivacional @` + "\u2063" + `USUARIO

- Eu tuito uma mensagem motivacional para o usuário marcado
- Por exemplo:
/motivacional @` + "\u2063" + `evaristocosta
`

var usernameRegexp = regexp.MustCompile(`@([a-zA-Z0-9_]{1,15})`)

// inspirationalRun picks a random inspirational method and sends it to a user.
// If no user is specified, it tries to find a user at random on Twitter.
func inspirationalRun(msg Message) error {
	// Try to match a tagged username.
	var tagged string
	var err error
	if usernameRegexp.MatchString(msg.Args) {
		tagged = usernameRegexp.FindStringSubmatch(msg.Args)[1]
	}
	if tagged == "" {
		if tagged, err = twitter.GetRandomUser(config.RandomUserWOEID); err != nil {
			switch msg.Type {
			case "tweet", "mention":
				_, err := twitter.PostTweetAt(msg.User, config.GetRandomUserFailed)
				return err
			case "tweetreply":
				_, err := twitter.PostTweetReply(msg.User, config.GetRandomUserFailed, msg.ReplyID)
				return err
			case "dm":
				return twitter.SendDM(msg.User, config.GetRandomUserFailed)
			}
			return ErrInvalidMessage
		}
	}
	content := inspirationalPhrases[rand.Intn(len(inspirationalPhrases))]
	content += " @" + tagged
	_, err = twitter.PostTweet(msg.User, content)
	return err
}

var inspirationalPhrases = []string{
	`"Sem dor, sem ganhos" adversidades são obstáculos que você só precisa de motivação e autoconfiança para ultrapassa-los.`,
	`80% dos seus resultados vêm de 20% das suas ações.`,
	`90% do sucesso baseia-se simplesmente em persistir.`,
	`A alegria está na luta, na tentativa, no sofrimento envolvido. Não na vitória propriamente dita.`,
	`A arte de vencer aprende-se nas derrotas.`,
	`A chave do sucesso da Sony e para tudo nos negócios é... não seguir os outros.`,
	`A coisa mais difícil é a decisão de agir, o resto é apenas tenacidade.`,
	`A coisa mais valiosa que você pode fazer é um erro, você não aprende nada sendo perfeito.`,
	`A criação de mil florestas está em uma semente.`,
	`A definição de sucesso varia de pessoa para pessoa. Para mim, sucesso é paz anterior.`,
	`A disciplina é a parte mais importante do sucesso.`,
	`A distância entre a insanidade e a genialidade é medida pelo sucesso.`,
	`A distância entre disciplina e a realidade chama-se sonho.`,
	`A dor é uma advertência, assim como os pequenos prejuízos nos negócios, nos ensinam a ser prudentes.`,
	`A educação custa dinheiro. Mas, em seguida, o mesmo acontece com a ignorância.`,
	`A esperança não é um sonho, mas uma maneira de traduzir os sonhos em realidade.`,
	`A esperança é algo maravilhoso e belo, uma lâmpada iluminada em nosso coração.`,
	`A esperança é cheia de confiança.`,
	`A esperança é o motor da vida. `,
	`A esperança és uma luz na direção do futuro.`,
	`A experiência é o melhor professor que se pode ter.`,
	`A felicidade não é algo pronto. Ela vem de suas próprias ações.`,
	`A felicidade é assim: enquanto muitos esperam, outros a buscam, tenha em mente que você é senhor de seu destino.`,
	`A felicidade é feita de metas realistas, dentro daquilo que a gente pode construir e vivenciar de verdade.`,
	`A felicidade é uma borboleta que, sempre que perseguida, parecerá inatingível; no entanto, se você for paciente, ela pode pousar no seu ombro.`,
	`A forma mais comum com que as pessoas exercem o seu poder é pensar que eles não têm poder.`,
	`A função da liderança é produzir mais líderes, não mais seguidores.`,
	`A grandeza não consiste em receber honras, mas em merecê-las.`,
	`A imaginação é mais importante que o conhecimento.`,
	`A liderança é uma poderosa combinação de estratégia e caráter. Mas se tiver de passar sem um, que seja estratégia.`,
	`A lógica pode levar de um ponto A a um ponto B. A imaginação pode levar a qualquer lugar.`,
	`A maior habilidade de um líder é desenvolver habilidades extraordinárias em pessoas comuns.`,
	`A maior recompensa pelo nosso trabalho não é o que nos pagam por ele, mas aquilo em que ele nos transforma.`,
	`A maioria das pessoas teria sucesso em coisas pequenas, se eles não estivessem preocupados com grandes ambições. E para os anos bissextos, uma frase bônus para você.`,
	`A maioria dos sucessos brotam de um obstáculo ou de um fracasso. Eu me tornei um desenhista porque eu falhei em minha meta de me tornar um executivo de sucesso.`,
	`A melhor maneira de encontrar seu cliente é ser encontrado por ele.`,
	`A melhor maneira de aprender é fazendo, seja o que é for.`,
	`A melhor maneira de prever o futuro é criá-lo.`,
	`A melhor maneira de sermos enganados é julgar que somos mais espertos do que os outros.`,
	`A melhor maneira de ter uma boa ideia é ter várias ideias. `,
	`A melhor vingança é um sucesso estrondoso.`,
	`A melhor época para plantar uma árvore foi há 20 anos. A segunda melhor é agora.`,
	`A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original.`,
	`A mente é seu próprio lugar, e em si pode fazer um céu do inferno, um inferno do céu.`,
	`A mente é tudo. Você se torna aquilo que você pensa.`,
	`A motivação da nossa vida é a felicidade.`,
	`A motivação é o que faz o empreendedor começar e o hábito é o que nos faz continuar.`,
	`A motivação é resultado dos estados psicológicos, pessoais e profissionais de cada indivíduo, o equilíbrio entre eles é o caminho para o sucesso.`,
	`A paciência é a chave para todos os problemas que não dependem de você.`,
	`A pedra que no papel nem serve para desenhar uma reta, dentro d'água faz círculos perfeitos.`,
	`A pessoa que diz que não pode ser feito não deve interromper a pessoa que está fazendo.`,
	`A pessoa que percebe como conduzir o talento coletivo de sua organização irá arrasar seus concorrentes.`,
	`A primeira razão para o fracasso de alguém é escutar amigos, família e vizinhos.`,
	`A primeira regra de qualquer tecnologia utilizada nos negócios é que a automação aplicada a uma operação eficiente aumentará a eficiência. A segunda é que a automação aplicada a uma operação ineficiente aumentará a ineficiência.`,
	`A qualidade de vida de uma pessoa é diretamente proporcional ao seu compromisso com a excelência, independentemente do seu campo escolhido ou esforço.`,
	`A questão essencial não é "o quanto ocupado você está", mas sim "com o que você está ocupado".`,
	`A questão não é quem vai me deixar; mas sim, quem vai me impedir.`,
	`A questão não é ter o problema, mas a forma como reagir a ele.`,
	`A recompensa de uma coisa bem feita é tê-la feito.`,
	`A sabedoria de um homem não está em não errar, chorar, se angustiar e se fragilizar, mas em usar seu sofrimento como alicerce de sua maturidade.`,
	`A simplicidade é o último grau de sofisticação.`,
	`A sorte passa na frente de todo mundo. Alguns agarram e outros não.`,
	`A sua cabeça é fértil? Você só fala abobrinha? Plante as abobrinhas e saia vendendo.`,
	`A sua estrada é somente sua. Outros podem acompanhá-lo, mas ninguém pode andar por você.`,
	`A sua vida é 10% do que acontece contigo e 90% de como você reage a isso.`,
	`A teoria sempre acaba, mais cedo ou mais tarde, assassinada pela experiência.`,
	`A tomada de riscos é a pedra angular dos impérios.`,
	`A vida encolhe ou expande em proporção com a sua coragem.`,
	`A vida muda na proporção da sua coragem.`,
	`A vida não tem limitações, exceto as que você cria.`,
	`A vida não é medida pelo número de respirações que damos, mas pelos momentos que nos tiram a respiração.`,
	`A vida não é sobre ter, é sobre dar e ser.`,
	`A vida é 10% do que acontece comigo e 90% de como eu reajo a isso.`,
	`A vida é melhor para aqueles para quem fazem o possível para terem o melhor.`,
	`A vida é melhor para aqueles que fazem o possível para ter o melhor.`,
	`A vida é o que acontece com você enquanto você está ocupado fazendo planos.`,
	`A vida é o que fazemos dela, sempre foi, e sempre será.`,
	`A vida é sobre criar impacto, não uma renda.`,
	`A vida é um longo caminho que começamos a trilhar desde o primeiro dia, no começo engatinhando, depois caminhando passo a passo até conquistarmos a confiança necessária para correr, sim, correr, pois o caminho é longo e o sucesso não espera.`,
	`A vitória pertence ao mais perseverante.`,
	`A vontade de questionar é a base mais forte para horizontes mais amplos.`,
	`A única coisa que está entre você e seu objetivo é a história que você continua inventando a si mesmo o motivo porque você não pode alcançá-lo.`,
	`A única coisa que separa você do seu sucesso, são as desculpas que você dá para não fazer as coisas.`,
	`A única coisa ruim do planejamento é que as coisas nunca ocorrem como foram planejadas.`,
	`A única maneira de fazer um excelente trabalho é amar o que você faz.`,
	`A única pessoa livre é aquela que não tem medo do ridículo.`,
	`A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.`,
	`Acredite em você.`,
	`Acredite no que quiser e acredite piamente. E se preciso, mude de opinião.`,
	`Acredite no seu potencial, procure motivar-se todos os dias, mantenha sua autoestima sempre elevada, você realizará grandes feitos em sua vida.`,
	`Acredite que você pode, assim você já está no meio do caminho.`,
	`Acredito que o objetivo da nossa vida seja a busca da felicidade.`,
	`Administração é fazer as coisas direito. Liderança é fazer as coisas certas.`,
	`Ainda não encontrei homem algum bem-sucedido na vida que não houvesse antes sofrido derrotas temporárias.`,
	`Aja como se você já fosse um sucesso tremendo, e tão certo como eu estou aqui hoje, você vai se tornar um sucesso.`,
	`Ando devagar, mas nunca ando para trás.`,
	`Antes de começar, é preciso um plano, e depois de planejar, é preciso execução imediata.`,
	`Antes que diga que não consegue fazer alguma coisa, experimente tentar fazê-la.`,
	`Ao observar com que talento criativo resolvemos problemas na vida particular, poderemos, então, transferir tal habilidade para o campo profissional.`,
	`Aprender mais rápido que seus concorrentes pode ser sua única vantagem competitiva sustentável.`,
	`Aprender é a única coisa que a mente nunca se cansa, nunca tem medo e nunca se arrepende.`,
	`Aquele que não luta pelo futuro que quer, deve aceitar o futuro que vier.`,
	`Aquele que não tem um objetivo, raramente sente prazer em qualquer empreendimento.`,
	`Arranje tempo para deliberar, mas quando chegar o tempo de agir, pare de pensar e faça.`,
	`As batalhas que contam não são apenas as medalhas de ouro. As lutas dentro de si, as batalhas invisíveis dentro de todos nós, é o que vale a pena.`,
	`As coisas não acontecem. Fazemos com que elas aconteçam.`,
	`As coisas que são difíceis de serem ditas, geralmente são as mais importantes.`,
	`As companhias prestam muita atenção ao custo de fazer alguma coisa. Deviam preocupar-se mais com os custos de não fazer nada.`,
	`As dificuldades e obstáculos são matéria-prima para o verdadeiro empreendedor.`,
	`As pessoas bem-sucedidas estão 100% convencidas de que são mestres do seu próprio destino, não são criaturas de circunstâncias: elas criam circunstâncias, se as circunstâncias ao seu redor forçam para que elas mudem.`,
	`As pessoas costumam dizer que a motivação não dura para sempre. Bem, nem o efeito do banho, por isso recomenda-se diariamente.`,
	`As pessoas fariam mais se não julgassem tantas coisas impossíveis.`,
	`As pessoas me perguntam qual é o papel que mais gostei de interpretar. Eu sempre respondo: o próximo.`,
	`As pessoas não gostam que você venda para elas. Mas lembrese que elas adoram comprar.`,
	`As pessoas não vão ter tempo para você se você está sempre irritado ou reclamando.`,
	`As pessoas que alcançam seu potencial pensam em aperfeiçoamento.`,
	`As pessoas que não correm riscos geralmente cometem cerca de 2 erros por ano. Pessoas que assumem riscos geralmente cometem cerca de 2 grandes erros por ano`,
	`As pessoas são parecidas em suas promessas. Elas só diferem em seus atos.`,
	`As únicas respostas interessantes são aquelas que destroem as perguntas.`,
	`Barulho não prova nada. Uma galinha bota um ovo e cacareja como se estivesse botado um asteróide.`,
	`Bem feito é melhor do que bem explicado.`,
	`Bons líderes são forjados, não nascem prontos.`,
	`Cada adversidade traz consigo a semente de um benefício equivalente.`,
	`Cada criança é um artista. O problema é permanecer um artista depois que crescemos.`,
	`Cada dia é uma nova chance para ser melhor. Não melhor que os outros. Melhor que nós mesmos.`,
	`Cada pessoa forja seu próprio destino.`,
	`Cada vez que você mente, mesmo uma pequena mentira inofensiva, existem fortes forças empurrando você em direção ao fracasso.`,
	`Caia 7 vezes. Levante-se 8.`,
	`Cerca de 40% de uma decisão se baseia em fatos, provas e oportunidades; 60% dependem do grau de compreensão, confiança e empatia com a pessoa ou a idéia em questão.`,
	`Chame o sucesso para fazer parte de sua vida. Acredite no seu potencial criador, seja inovador, treine sua mente para vencer, estipule metas e, principalmente, lute por seus ideais.`,
	`Coisas incríveis no mundo nunca são feitas por uma única pessoa, mas por uma equipe.`,
	`Com talento ganhamos partidas; com trabalho em equipe e inteligência ganhamos campeonatos.`,
	`Comece de onde você está. Use o que você tiver. Faça o que você puder.`,
	`Comece onde está. Use o que você tem. Faça o que puder.`,
	`Como é maravilhoso que ninguém precise esperar um momento antes de começar a melhorar o mundo.`,
	`Concentre-se no que está buscando e não no que está deixando para trás. `,
	`Confiança grande demais é algo destinados aos menos talentosos como um prêmio de consolação.`,
	`Confiança grande demais é algo destinados aos menos talentosos como um prêmio de consolação.`,
	`Constantemente se pergunte como pode fazer melhor as coisas e continue se questionando.`,
	`Construa seus próprios sonhos, ou alguém vai contratá-lo para construir os seus.`,
	`Continue andando. Haverá a chance de você ser barrado por um obstáculo, talvez por algo que você nem espere. Mas eu nunca ouvi falar de ninguém que foi barrado enquanto estava parado.`,
	`Continue, siga em frente.`,
	`Contrate as melhores pessoas que puder para trabalhar com você, e confie nelas de uma maneira que possam realizar o melhor trabalho para você e para elas próprias.`,
	`Coragem é a resistência e o domínio do medo, não a ausência dele.`,
	`Crie algo que as pessoas queiram compartilhar.`,
	`Cérebro é como um paraquedas: só funciona quando aberto.`,
	`Da próxima vez que alguém reclamar que você cometeu um erro, diga a essa pessoa que talvez isso seja uma boa coisa, porque sem imperfeição nem você nem eu existiríamos.`,
	`Daqui a 20 anos você estará mais decepcionado pelas coisas que você não fez, do que pelas que fez.`,
	`Dar menos que seu melhor é sacrificar o dom que você recebeu.`,
	`De fato, não fracassei ao tentar, cerca de 10.000 vezes. Simplesmente, encontrei 10.000 maneiras que não funcionam.`,
	`Decidir o que não fazer é tão importante quanto decidir o que fazer.`,
	`Definir um objetivo é o ponto de partida de toda a realização.`,
	`Democracia é oportunizar a todos o mesmo ponto de partida. Quanto ao ponto de chegada, depende de cada um.`,
	`Descobri que, quanto mais eu trabalho, mais sorte eu pareço ter.`,
	`Descobri que, se você tem vontade de viver e curiosidade, dormir não é a coisa mais importante.`,
	`Determinadas coisas capturam o seu olho, mas leve a cabo apenas aquelas que capturam seu coração.`,
	`Deus deu ao homem uma boca e dois ouvidos para que ouça duas vezes mais do que fala.`,
	`Deve-se utilizar a força do oponente a nosso favor.`,
	`Devemos crer que somos dotados de alguma coisa, e que essa coisa, deve ser atingida a qualquer custo.`,
	`Devemos formular metas nítidas, definidas, específicas e claras, rezar por elas e dar-lhes nosso esforço e imaginação.`,
	`Devemos prometer somente o que podemos entregar e entregar mais do que prometemos.`,
	`Digo a todo jovem que quer ser empreendedor que é preciso se superar.`,
	`Diz-se que o homem vale pelo que sabe, mas vale mais aquele que sabe como dizer aquilo que sabe. `,
	`Dois homens olham pela janela. Um vê a lama e o outro vê as estrelas. `,
	`Duas estradas divergiam em uma bifurcação, e eu peguei a menos percorrida. E isso fez toda a diferença.`,
	`Durante milhões de anos, a humanidade viveu exatamente como os animais. Então aconteceu alguma coisa que desencadeou o poder da nossa imaginação. Nós aprendemos a falar e aprendemos a ouvir.`,
	`Dá-se glória apenas para aqueles que sempre sonharam com ela.`,
	`Educação nunca foi despesa. Sempre foi investimento com retorno garantido.`,
	`Em Japonês, não existe a expressão "BOA SORTE." A mais aproximada é "ESFORCE-SE".`,
	`Em qualquer corrida ao ouro, aqueles que mais ganham são sempre os que vendem as picaretas.`,
	`Em qualquer direção que você vá, vá com todo seu coração.`,
	`Embora ninguém possa voltar atrás e começar tudo de novo, qualquer um pode ter um ótimo final.`,
	`Empreendedores são aqueles que entendem que há uma pequena diferença entre obstáculos e oportunidades e são capazes de transformar ambos em vantagem. `,
	`Encontre frequentemente seus contatos de negócios para conversas não-comerciais.`,
	`Escolha uma ideia. Faça dessa ideia a sua vida. Pense nela, sonhe com ela, viva pensando nela. Deixe cérebro, músculos, nervos, todas as partes do seu corpo serem preenchidas com essa ideia. Esse é o caminho para o sucesso.`,
	`Escreva algo que valha a pena ler, ou faça alguma coisa que valha a pena escrever.`,
	`Escreva algo que valha a pena ser lido, ou faça algo que valha a pena ser escrito.`,
	`Essa é exatamente a pergunta que todos deveriam estar se perguntando, por que não? -- Por que não você? Por que não agora...?`,
	`Estar disposto não é o suficiente; devemos fazer.`,
	`Estou convencido que metade do que separa os empreendedores bem sucedidos de todo o resto é a pura perseverança.`,
	`Estratégia é a definição de como recursos serão alocados para se atingir um determinado objetivo.`,
	`Eu acredito em imersão total, se você quer ser rico, você tem que programar sua mente para ser rico. Você tem que desaprender todos os pensamentos que estavam fazendo você ser pobre e substituí-los com novos pensamentos, pensamentos de ricos.`,
	`Eu acredito que cada direito implica em uma responsabilidade, cada oportunidade em uma obrigação.`,
	`Eu aprendi que as pessoas vão esquecer o que você disse, as pessoas vão esquecer o que você fez, mas as pessoas nunca esquecerão como você as fez sentir.`,
	`Eu aprendi que erros podem ser tão bons professores quanto o sucesso.`,
	`Eu atribuo o meu sucesso a isso: eu nunca dei ou tomei qualquer desculpa.`,
	`Eu descobri que sempre tenho escolhas. E muitas vezes, trata-se apenas de uma escolha de atitude.`,
	`Eu devo meu sucesso a meu hábito de respeitosamente ouvir conselhos e fazer exatamente o contrário.`,
	`Eu falhei algumas vezes em minha vida, é por isso que eu consegui.`,
	`Eu falhei várias, várias e várias vezes em minha vida, e é por isso que eu tive sucesso.`,
	`Eu não falhei. Só descobri muitos caminhos que não eram o certo.`,
	`Eu não sou um produto de minhas circunstâncias. Eu sou um produto de minhas decisões.`,
	`Eu odiava cada minuto do treinamento, mas eu disse, Não pare. Sofra agora para viver o resto de sua vida como um campeão.`,
	`Eu quero que você se coloque contra a parede. Dê a si mesmo nenhuma escolha senão ter sucesso. Deixe as consequências do fracasso se tornarem tão terríveis e tão impensáveis, que você não terá escolha a não ser fazer o que for preciso para ter sucesso.`,
	`Eu sou tão orgulhoso das coisas que fizemos, como sou das coisas que temos feito. Inovar é dizer não a milhares de coisas.`,
	`Eu tenho coragem de morrer. O que eu quero saber é: você tem coragem de viver?`,
	`Eu tive todas as desvantagens necessárias para o sucesso.`,
	`Existe apenas um chefe, o cliente. E ele pode demitir todos na empresa, desde o presidente, simplesmente gastando o dinheiro em outro lugar.`,
	`Existe o risco que você não pode jamais correr e existe o risco que você não pode deixar de correr. `,
	`Existe somente um momento para ser feliz. Esse momento é o PRESENTE, e tem duração do instante que passa.`,
	`Explore, sonha, descubra.`,
	`Falhar não é o resultado, falhar é não tentar. Não tenha medo de falhar.`,
	`Falta de tempo é desculpa daqueles que perdem tempo por falta de métodos.`,
	`Fazemos nossos caminhos e lhes chamamos destino.`,
	`Fazer as coisas certas é mais importante do que fazer as coisas direito`,
	`Faça as coisas de maneira diferente de cada vez. Um dia, você vai fazer direito. O fracasso é seu amigo.`,
	`Faça de tudo uma vez... E o que mais gostar, faça duas, três...`,
	`Faça o que puder com o que tiver, onde estiver.`,
	`Faça o óbvio, de maneira simples, no momento certo, trabalhando com os melhores e faça a diferença.`,
	`Faça ou não faça. A tentativa não existe.`,
	`Faça poeira, em vez de engolir poeira.`,
	`Feliz aquele que transfere o que sabe e aprende o que ensina.`,
	`Fique contente em agir. Deixe a fala para os outros.`,
	`Fiquei impressionado com a urgência do fazer.`,
	`Foco é tudo, dispersão é nada.`,
	`Foque em um pino de boliche por vez.`,
	`Frequentemente, o melhor marketing não parece realmente marketing.`,
	`Fácil é ditar regras. Difícil é segui-las.`,
	`Fácil é ouvir a música que toca. Difícil é ouvir a sua consciência.`,
	`Ganhar não é tudo, mas querer ganhar é.`,
	`Gestão não é nada mais do que motivar outras pessoas.`,
	`Grandes empreendedores estão confortáveis em estarem desconfortáveis.`,
	`Grandes líderes mudam de estilo para levantar a auto-estima de suas equipes. Se as pessoas acreditam nelas mesmas, é impressionante o que elas conseguem realizar.`,
	`Grandes mentes discutem ideias; mentes medianas discutem acontecimentos; mentes pequenas discutem pessoas.`,
	`Grandes realizações não são feitas por impulso, mas por uma soma de pequenas realizações.`,
	`Grandes visionários são importantes; Grandes administradores são fundamentais.`,
	`Habilidade só se ganha fazendo.`,
	`Haverá a chance de você ser barrado por um obstáculo, talvez por algo que você nem espere. Mas siga, até porque eu nunca ouvi falar de ninguém que foi barrado enquanto estava parado.`,
	`Há apenas duas maneiras de obter sucesso neste mundo: pelos próprios hábitos ou pela incompetência alheia.`,
	`Há apenas uma maneira de evitar críticas: não faça nada, não diga nada, e não seja nada.`,
	`Há cinco degraus para se alcançar a sabedoria: Calar, ouvir, lembrar, sair, estudar.`,
	`Há dois tipos de pessoa que vão te dizer que você não pode fazer a diferença neste mundo: as que têm medo de tentar e as que têm medo de que você se dê bem.`,
	`Há dois tipos de pessoas que não interessam a uma boa empresa: as que não fazem o que se manda e as que só fazem o que se manda.`,
	`Há dois tipos de pessoas: as que fazem o trabalho e as que reivindicam o mérito. Procure estar no primeiro grupo. Há menos concorrência.`,
	`Há duas espécies de tolos: os que não duvidam de nada e os que duvidam de tudo.`,
	`Há muitas razões ruins para começar uma empresa. Mas há apenas uma boa, legítima razão, e eu acho que você sabe qual é: mudar o mundo.`,
	`Há quem passe pelo bosque e só veja a lenha da fogueira.`,
	`Há três coisas que nunca voltam atrás: a flecha lançada, a palavra pronunciada e a oportunidade perdida.`,
	`Há três tipos de empresas: empresas que tentam levar os seus clientes onde eles não querem ir; empresas que ouvem os seus clientes e depois respondem às suas necessidades; e empresas que levam os seus clientes aonde eles ainda não sabem que querem ir.`,
	`Há uma regra para industriais que é: Fazer a mercadoria da melhor qualidade possível, no menor custo possível, pagando o mais alto salário possível.`,
	`Há várias maneiras de ser entendido: ser claro é uma delas.`,
	`Ignorar é a forma mais elegante de se defender da maldade.`,
	`Inclua em teu trabalho o objetivo de servir e fazer o bem aos demais e conhecerás o que é trabalhar com felicidade.`,
	`Independente do que você faça, seja diferente. Se você for diferente, você se destacará.`,
	`Inovação é o que distingue um líder de um seguidor.`,
	`Inteligente não é quem sabe para onde ir, mas quem aprendeu para onde não deve voltar.`,
	`Inteligência é a capacidade de inovar ao fazer essas conexões.`,
	`Inteligência é a habilidade de se adaptar às mudanças.`,
	`Inteligência é uma capacidade mental bastante geral que, entre outras coisas, envolve a habilidade de raciocinar, planejar, resolver problemas, pensar de forma abstrata, compreender idéias complexas, aprender rápido e aprender com a experiência.`,
	`Intenção sem ação é ilusão. Ouse fazer e o poder lhe será dado.`,
	`Jogar de modo seguro sem tomar riscos, é um atalho para a pobreza.`,
	`Jogue fora suas amarras, navegue para longe do porto seguro, pegue os ventos em suas velas. Explore, sonha, descubra.`,
	`Julgamos a nós mesmos pelo que nos sentimos capazes de fazer, enquanto os outros nos julgam pelo que já fizemos.`,
	`Já dizia a canção, quem sabe faz a hora, não espera acontecer.`,
	`Já que você vai pensar de qualquer jeito, pense grande.`,
	`Lembre-se de olhar para o alto, para as estrelas, e não para baixo, para os seus pés.`,
	`Leva-se 20 anos para construir uma reputação e cinco minutos para destruí-la. Se você pensar sobre isso, fará as coisas de maneira diferente.`,
	`Levante-se! Tenha coragem e mãos à obra! Use tudo o que você possui para adquirir entendimento.`,
	`Leve porrada, mas nunca deixem abalar a sua essência.`,
	`Liderança é a capacidade de tomar iniciativas em situações de planejar, organizar a ação e de suscitar colaboração.`,
	`Liderança é fazer as pessoas trabalharem para você quando não são obrigadas.`,
	`Limitações vivem apenas em nossas mentes. Mas se usarmos nossa imaginação, nossas possibilidades tornam-se ilimitadas.`,
	`Lucro é subproduto das coisas bem feitas.`,
	`Lute com determinação, abrace a vida com paixão, perca com classe e vença com ousadia.`,
	`Lute sabendo que no final a vitória sempre vem e quanto maior for a luta, maior será a sua vitória.`,
	`Líderes levam pessoas a níveis "impossíveis" de desempenho e depois deixam o caminho livre.`,
	`Marketing é importante demais para ser deixado para o departamento de marketing.`,
	`Maturidade é viver em paz com aquilo que não se pode mudar.`,
	`Melhor maneira de vender algo: não vender nada. Ganhe a consciência, o respeito e a confiança daqueles que podem comprar.`,
	`Melhorar geralmente significa fazer algo que nunca fizemos antes.`,
	`Meu objetivo é simples. É a compreensão completa do Universo, por que ele é assim e por que existe de uma maneira geral.`,
	`Meu trabalho não é o de pegar leve com as pessoas, meu trabalho é a de tornar elas melhores.`,
	`Milhões viram a maçã cair, mas foi Newton quem perguntou por que.`,
	`Motivar é criar interesse pelo tema e vontade, esse ânimo e auto-ajuda vão nos ajudar a progredir em conhecimentos e nas tarefas profissionais.`,
	`Mudar o mundo é mudar um mundo de cada vez.`,
	`Mude seus pensamentos e você muda seu mundo.`,
	`Muitas coisas não ousamos empreender por parecerem difíceis; entretanto, são difíceis porque não ousamos empreendê-las.`,
	`Muitas das falhas da vida ocorrem quando não percebemos o quão próximos estávamos do sucesso na hora em que desistimos.`,
	`Muitas pessoas não têm sucesso após um tempo. O que elas fundamentalmente fazem errado? Negligenciam o futuro.`,
	`Muitas pessoas querem andar de limusine com você, mas o que você quer é alguém que irá pegar o ônibus com você quando a limusine estiver quebrada.`,
	`Muitas vezes, tudo se resume apenas a uma mudança de atitude.`,
	`Muito líderes de grandes empresas, penso eu, não acreditam que a mudança seja possível. Mas se você olhar a história, as coisas mudam e se seu negócio é estático, você certamente terá problemas.`,
	`Muitos de nós não estamos vivendo nossos sonhos porque estamos vivendo nossos medos.`,
	`Na geração de soluções, 20% têm a ver com dinheiro -- e 80% com pessoas: elas criam soluções.`,
	`Na prática do dia-a-dia é que colocaremos a prova tudo aquilo que os mestres nos ensinaram e muitas vezes veremos que não era bem daquela maneira.`,
	`Na verdade, aos poucos descobrimos que os outros são nossos espelhos e nos devolvem a luz, as ações e os sentimentos que lhe passamos.`,
	`Nada mais perigoso do que o sucesso de ontem.`,
	`Nada substitui a persistência, nem mesmo o talento.`,
	`Nada é difícil se for dividido em pequenas partes.`,
	`Nada é impossível, a própria palavra diz ‘eu sou possível’ [i’m possible, em inglês].`,
	`Nada é mais desafiador do que superar uma situação não planejada.`,
	`Nada é permanente, exceto a mudança.`,
	`Negociar seus princípios é um péssimo negócio.`,
	`Nem teus piores inimigos podem fazer tanto dano como teus próprios pensamentos.`,
	`Nenhum de nós juntos. é tão inteligente quanto todos nós`,
	`Nenhum de nós é tão esperto quanto todos nós.`,
	`Nenhum obstáculo é tão grande se sua vontade de vencer for maior.`,
	`Nenhum pássaro voa alto demais, se voa com as próprias asas.`,
	`Nenhuma empresa é melhor do que o seu administrador permite.`,
	`Ninguém jamais afundou em seu próprio suor.`,
	`Ninguém pode fazer você se sentir inferior sem o seu consentimento.`,
	`Ninguém vai se importar com os seus fracassos, nem você deveria.`,
	`No futuro haverá dois tipos de gestores: os rápidos e os mortos.`,
	`No meio da confusão, encontre a simplicidade. A partir da discórdia, encontre a harmonia. No meio da dificuldade reside a oportunidade.`,
	`No meio de qualquer dificuldade encontra-se a oportunidade.`,
	`No mundo dos negócios nunca se obtém aquilo que se quer, mas sim aquilo que se negocia.`,
	`No mundo dos negócios todos são pagos em duas moedas: dinheiro e experiência. Agarre a experiência primeiro, o dinheiro virá depois.`,
	`Nos dias de hoje, cada vez mais, acentua-se a necessidade de ser forte. Mas não há uma fórmula mágica que nos faça chegar à força sem que antes tenhamos provado a fraqueza.`,
	`Nos negócios, as oportunidades são como ônibus, há sempre um outro vindo.`,
	`Nossas vidas começam a terminar no dia em que nos calamos sobre as coisas que importam.`,
	`Nosso maior medo não deve ser o fracasso, mas ser bem-sucedidos em algo que não importa.`,
	`Numa época de crise em que todos choram, há sempre alguém que se lembra de fabricar lenços.`,
	`Nunca alguém tão grande se fez tão pequeno para tornar grandes os pequenos.`,
	`Nunca avalie a altura de uma montanha até que atinja o cume. Verá então com era baixa.`,
	`Nunca deixe que nenhum limite tire de você a ambição da auto-superação.`,
	`Nunca desista de um sonho só por causa do tempo que você vai levar para realizá-lo. O tempo vai passar de qualquer forma.`,
	`Nunca interrompa seu inimigo quando ele estiver cometendo um erro.`,
	`Nunca é tarde demais para ser o que você poderia ter sido.`,
	`Nunca é tão fácil perder-se como quando se julga conhecer o caminho.`,
	`Não acredite que a única forma de seu negócio funcionar é através da perfeição. Não busque a perfeição. Busque o sucesso.`,
	`Não acredito em circunstância: os indivíduos de sucesso são aqueles que saem e procuram as condições que desejam; e, se não as encontram, criam-nas.`,
	`Não adianta encher de perfume se o que falta é a essência.`,
	`Não basta reconhecer um erro. É preciso atitude forte para reparálo e perseverança para jamais repeti-lo.`,
	`Não brigue com o problema. Resolva-o.`,
	`Não chegar a tentar é sofrer a inestimável perda do que poderia ter sido.`,
	`Não conheço a chave para o sucesso, mas a chave para o fracasso é tentar agradar a todo mundo.`,
	`Não construa links, construa relacionamentos.`,
	`Não corrigir nossas falhas é o mesmo que cometer novos erros.`,
	`Não deixe para amanhã.`,
	`Não desista jamais e saiba valorizar quem te ama, esses sim merecem seu respeito. Quanto ao resto, bom, ninguém nunca precisou de restos para ser feliz.`,
	`Não desista nunca. Nunca. Nunca. Nunca. Nunca.`,
	`Não devo para bancos e só gasto aquilo que posso investir.`,
	`Não dá pra fazer as 2 coisas ao mesmo tempo.`,
	`Não encontre um defeito, encontre uma solução. `,
	`Não espere as condições ideias, elas nunca chegam.`,
	`Não faça da sua vida um rascunho, poderá não ter tempo de passá-la a limpo.`,
	`Não fique aí remando contra a maré. Se não for pra ser, não vai ser.`,
	`Não foi de um salto que os grandes homens chegaram ao topo do êxito; mas, sim, trabalhando enquanto os outros dormiam.`,
	`Não haverá borboletas se a vida não passar por longas e silenciosas metamorfoses.`,
	`Não há engarrafamentos ao longo da milha extra.`,
	`Não há melhor pregador que a formiga, que nada diz.`,
	`Não há nada que seja maior evidência de insanidade do que fazer a mesma coisa dia após dia e esperar resultados diferentes.`,
	`Não há nada tão inútil quanto fazer eficientemente o que não deveria ser feito.`,
	`Não há nenhuma maneira de ter sucesso nos negócios sem os mais altos padrões éticos.`,
	`Não há nobreza na pobreza. Eu fui um homem rico e eu fui um pobre homem. E eu escolho ser rico todas as vezes.`,
	`Não há um homem vivo que não possa fazer mais do que ele pensa que pode.`,
	`Não importa o que aconteceu com você no seu passado, você não é seu passado, você é os recursos e as capacidades que você aprendeu a partir dele. E essa é a base para toda a mudança.`,
	`Não importa o quão devagar você vá, desde que você não pare.`,
	`Não importa o quão ruim a vida possa ser, há sempre alguma coisa que você pode fazer e ter sucesso. Enquanto há vida, há esperança.`,
	`Não importa quantos passos você deu para trás. Importa quantos passos você vai dar para frente.`,
	`Não importa se você vai devagar, tanto quanto importa o fato de você não parar.`,
	`Não mude por ninguém, mude por você mesmo. Essa é a essência da mudança. Mudar porque queremos progredir e não porque queremos impressionar.`,
	`Não pergunte o que as pessoas podem fazer por você, se pergunte o que você pode fazer por você.`,
	`Não pergunte o que o seu país pode fazer por você; e sim, o que você pode fazer por seu país.`,
	`Não queira que a vida seja mais fácil. Deseje que você seja ainda melhor.`,
	`Não queira que a vida seja mais fácil. Deseje que você seja ainda melhor.`,
	`Não se preocupe com financiamento se você não precisa. Hoje, é mais barato começar um negócio do que jamais foi.`,
	`Não sei qual é a chave para o sucesso, mas a chave para o fracasso é tentar agradar a todos.`,
	`Não seja nunca a dessas almas frias e tímidas que não conhecem nem a vitória nem a derrota.`,
	`Não seja rico em dados e pobre em informação.`,
	`Não siga pelo caminho. Vá pela trilha.`,
	`Não somos ricos pelo que temos e sim pelo que não precisamos ter.`,
	`Não são os anos de sua vida que contam. É a vida em seus anos.`,
	`Não são os números e os objetivos que conduzem ao seu destino, mas sim as pessoas.`,
	`Não tenha medo de desistir do bom para perseguir o ótimo.`,
	`Não tenho quaisquer talentos especiais. Sou apenas imensamente curioso.`,
	`Não tente ser uma pessoa de sucesso. Em vez disso, seja uma pessoa de valor.`,
	`Não ter amigos no governo é regra fundamental para conseguir êxito.`,
	`Não viva para que a sua presença seja notada, mas para que a sua falta seja sentida.`,
	`Não é a montanha que conquistamos, mas a nós mesmos.`,
	`Não é com os pés que se sobe os degraus da carreira, é com a cabeça!`,
	`Não é o dinheiro. É a vontade de trabalhar mais e aprender mais do que todos quando se tratar de seu negócio. E se isso falhar, você aprende com a falha e faz melhor da próxima vez.`,
	`Não é o mais forte que sobrevive, nem o mais inteligente. Quem sobrevive é o mais disposto à mudança.`,
	`Não é o que oferecemos, mas o modo pelo qual oferecemos que determina o valor do presente.`,
	`Não é o que você faz para os seus filhos, mas o que você os ensinou a fazer por si mesmos, que irá torna-los serem humanos bem sucedidos.`,
	`Não é sobre ideias. É sobre fazer as ideias acontecerem.`,
	`Não é sobre o tempo, é sobre as escolhas. Como você está gastando suas escolhas?`,
	`Nós nos tornamos aquilo que pensamos.`,
	`Nós podemos facilmente perdoar uma criança que tem medo do escuro; a tragédia real da vida é quando os homens têm medo da luz.`,
	`Nós somos apenas uma espécie avançada de macacos em um planeta pequeno de uma estrela mediana. Mas nós conseguimos entender o Universo. Isso nos torna muito especiais.`,
	`O arquiteto de suas aflições e o destruidor de suas oportunidades de elevação -- é você mesmo.`,
	`O bom gerenciamento consiste em mostrar às pessoas medianas como fazer o trabalho de pessoas superdotadas.`,
	`O caminho para começar é parar de falar e começar fazer.`,
	`O Capital Humano, não o financeiro, deve ser o ponto de partida e a base contínua de uma estratégia bem-sucedida.`,
	`O capitalismo é a arma contra a pobreza.`,
	`O conformismo é o carcereiro da liberdade e o inimigo do crescimento.`,
	`O custo de estar errado é menor do que o custo de não fazer nada.`,
	`O decadente se limita a comparecer ao trabalho e se deixar levar pela maré.`,
	`O dia de amanhã ainda ninguém usou. Pode ser seu!`,
	`O empreendedor é alguém que pula de um penhasco e constrói um avião na descida.`,
	`O entusiasmo é a maior força da alma. Conserva-o e nunca te faltará poder para conseguires o que desejas.`,
	`O essencial é ter na vida um ideal alevantado e definido com aptidão e perseverança suficientes para o atingir.`,
	`O fracasso não é algo a ser evitado, você quer que ele aconteça bem rápido para que você possa progredir rapidamente.`,
	`O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.`,
	`O fundamental é manter sempre a mesma obsessão em alcançar o sucesso.`,
	`O futuro das organizações dependerá cada vez mais de sua capacidade de aprender coletivamente.`,
	`O grande segredo de uma boa vida é encontrar qual é o seu destino. E realizá-lo.`,
	`O guerreiro de sucesso é um homem médio, mas com um foco apurado.`,
	`O homem comum é exigente com os outros, o homem superior é exigente consigo mesmo. `,
	`O homem pode tanto quanto sabe.`,
	`O homem que não sabe comércio, não deve abrir um`,
	`O hábito de tolerar tudo pode ser a causa de muitos erros e de muitos perigos.`,
	`O importante, na minha opinião, não é colocar a culpa em alguém, mas averiguar o que causou o erro.`,
	`O insucesso é apenas uma oportunidade para recomeçar de novo com mais inteligência.`,
	`O liderado será reflexo da sua liderança, então quem espera lealdade, primeiro deve ser leal.`,
	`O lucro é o subproduto das coisas bem-feitas.`,
	`O líder mais bem-sucedido é aquele que tem uma visão do que ainda não foi realizado.`,
	`O maior erro é não arriscar por medo de errar.`,
	`O maior inimigo de um plano, é um plano perfeito.`,
	`O maior líder é aquele que reconhece sua pequenez, extrai força de sua humildade e experiência da sua fragilidade.`,
	`O maior risco é não assumir riscos... em um mundo que está mudando realmente rápido, a única estratégia que é garantia de falha é não assumir riscos.`,
	`O maior território inexplorado no mundo é o espaço entre as nossas orelhas.`,
	`O mais forte da espécie não é o mais forte ou mais inteligente, e sim, o mais receptivo a mudança.`,
	`O mais importante ingrediente na fórmula do sucesso é saber como lidar com as pessoas.`,
	`O mais incompreensível do mundo é que ele seja compreensível.`,
	`O melhor cliente é aquele que já temos.`,
	`O mundo é como um prisma -- o que você vê, depende de como você gira o cristal.`,
	`O orientador brilhante de executivos é aquele que faz surgir o brilho do cliente.`,
	`O perigoso não é pensar grande e não conseguir; o perigoso é pensar pequeno e conseguir.`,
	`O pessimista se queixa do vento, o otimista espera que ele mude, o realista ajusta as velas.`,
	`O poder só sobe à cabeça quando encontra o local vazio.`,
	`O ponto de partida de qualquer conquista é o desejo.`,
	`O primeiro dever da inteligência é desconfiar dela mesma.`,
	`O primeiro passo para chegar a algum lugar é decidir que você não quer mais ficar onde está.`,
	`O primeiro passo rumo ao sucesso é dado quando você se recusa ao ser um refém do ambiente em que se encontra.`,
	`O primeiro requisito para o sucesso é desenvolver a habilidade de focar e aplicar a sua energia física e mental ao problema que você tem na mão -- sem se cansar.`,
	`O principal perigo na vida é que você pode tomar precauções demais.`,
	`O problema não é o problema -- o problema é a atitude com relação ao problema.`,
	`O profissional hoje não é mais local, e sim global.`,
	`O que nos parece uma provação amarga pode ser uma bênção disfarçada.`,
	`O que pode ser medido, pode ser melhorado`,
	`O que une uma equipe é quando um cobre as fraquezas do outro.`,
	`O segredo de meu sucesso é pagar como se fosse perdulário e comprar como se estivesse quebrado.`,
	`O segredo do empreendedorismo é ter 100% de convicção com apenas 80% da resposta.`,
	`O segredo para contratar com sucesso é esse: olhe paras as pessoas que querem mudar o mundo.`,
	`O ser humano aproveita, em média, apenas 20% do seu potencial produtivo; logo, 80% estão latentes -- hibernando.`,
	`O ser humano por sua própria natureza tem uma visão limitada sobre o mundo.`,
	`O seu tempo de vida é limitado, então não o gaste vivendo a vida de outra pessoa.`,
	`O sol nasceu para todos.`,
	`O sucesso consegue-se com decisão, confiança, persistência; e não, com desânimo, indecisão, lamúrias.`,
	`O sucesso normalmente vem para quem está ocupado demais para procurar por ele.`,
	`O sucesso não consiste em não errar, mas não cometer os mesmos equívocos mais de uma vez.`,
	`O sucesso não espera.`,
	`O sucesso não requer nenhuma explicação; a falha não permite nenhum álibi.`,
	`O sucesso resulta de cem pequenas coisas feitas de forma um pouco melhor. O insucesso, de cem pequenas coisas feitas de forma um pouco pior.`,
	`O sucesso tem muitos pais, mas o fracasso é órfão.`,
	`O sucesso é a soma de pequenos esforços -- repetidos dia sim, e no outro dia também.`,
	`O sucesso é a soma de pequenos esforços repetidos dia após dia.`,
	`O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.`,
	`O sucesso é pessoal e intransferível. Separe um tempo para definir o que é sucesso para você, depois corra atrás disso. Simples assim.`,
	`O sucesso é um símbolo de autoconfiança.`,
	`O trabalho afasta de nós três grandes males: o aborrecimento, o vício e a necessidade!`,
	`O trabalho em equipe é um malabarismo constante entre o interesse próprio e o interesse do grupo.`,
	`O trabalho é o grande libertador do homem; só a ociosidade o escraviza.`,
	`O único homem que jamais erra é aquele que nunca faz nada.`,
	`O único lugar em que o sucesso vem antes do trabalho é no dicionário.`,
	`O único lugar onde sucesso vem antes de trabalho é no dicionário. `,
	`O único modo de evitar os erros é adquirindo experiência; mas a única maneira de adquirir experiência é cometendo erros.`,
	`Obstáculos são aquelas coisas assustadoras que vemos quando afastamos os olhos do alvo. `,
	`Olha para si mesmo no espelho e se pergunte, o que eu quero fazer todos os dias para o resto de minha vida... e faça isso.`,
	`Olhar o futuro é enxergar a consequência do presente.`,
	`Oportunidade dança com aqueles que já estão no salão.`,
	`Oportunidades não surgem. É você que as cria.`,
	`Os analfabetos do século XXI não são aqueles que não sabem ler ou escrever, mas aqueles que se recusam a aprender, reaprender e voltar a aprender. `,
	`Os chefes são líderes mais através do exemplo do que através do poder.`,
	`Os covardes nunca começam, os fracassados nunca terminam, os vencedores nunca desistem.`,
	`Os desafios são o que tornam a vida interessante e superá-los é o que dá sentido à vida.`,
	`Os dias mais importantes na sua vida são o dia em que você nasce, e o dia em que você descobre o porquê.`,
	`Os dias prósperos não vêm por acaso; nascem de muita fadiga e persistência.`,
	`Os empreendedores falham, em média, 3,8 vezes antes do sucesso final. O que separa os bem-sucedidos dos outros é a persistência.`,
	`Os grandes líderes são como os melhores maestros - eles vão além das notas para alcançar a mágica dos músicos.`,
	`Os grandes navegadores devem sua reputação aos temporais e tempestades.`,
	`Os homens prudentes sabem tirar proveito de todas as suas ações, mesmo daquelas a que são obrigados pela necessidade.`,
	`Os milagres acontecem, às vezes. Mas é preciso trabalhar tremendamente para que aconteçam. `,
	`Os problemas não podem ser resolvidos em um mesmo nível de pensamento no qual foram gerados.`,
	`Os recursos precisam ser destinados às oportunidades e não aos problemas.`,
	`Os resultados são obtidos através da exploração de oportunidades, não pela solução de problemas`,
	`Os sonhadores são os salvadores do mundo.`,
	`Os vencedores falham, em média, 3 à 8 vezes antes do sucesso final. O que separa os bem-sucedidos dos outros é a persistência.`,
	`Os vencedores usam palavras que dizem "devo fazer" e "vou fazer".`,
	`Ou você corre do dia, ou durante o dia você corre.`,
	`Palavra e ação juntas não andam bem. Repare na natureza: trabalha continuamente, mas em silêncio.`,
	`Para alcançar o conhecimento, acrescente coisas todos os dias. Para alcançar a sabedoria, remova coisas todos os dias.`,
	`Para compreender as pessoas devo tentar escutar o que elas não estão dizendo, o que elas talvez nunca venham a dizer.`,
	`Para conquistar o sucesso, você precisa aceitar todos os desafios que vierem na sua frente. Você não pode apenas aceitar os que você preferir.`,
	`Para de perseguir o dinheiro e comece a perseguir o sucesso.`,
	`Para melhorar a qualidade de vida, melhore a qualidade de seus pensamentos.`,
	`Para mim, sucesso é paz anterior`,
	`Para o verdadeiro sucesso, pergunte a si mesmo 4 questões: por que? Por que não? Por que não eu? Por que não agora?`,
	`Para se fazer grandes coisas não se deve estar acima dos homens, mas junto deles.`,
	`Para se ter sucesso, é necessário amar de verdade o que se faz. Caso contrário, levando em conta apenas o lado racional, você simplesmente desiste. É o que acontece com a maioria das pessoas.`,
	`Para ser bem sucedido você precisa apenas de uma estrutura e um sonho.`,
	`Para ser vitorioso você precisa ver o que não está visível.`,
	`Para ter sucesso, o seu desejo de sucesso deve ser maior do que o seu medo do fracasso.`,
	`Pequenas oportunidades podem ser o começo de grandes oportunidades.`,
	`Pergunte sempre a cada ideia: a quem serves?`,
	`Perseverança é o trabalho duro que você faz depois de ter se cansado de fazer o trabalho duro que você já fez.`,
	`Pessoas de sucesso fazem o que pessoas mal sucedidas não querem fazer.`,
	`Pessoas que falham em planejar estão planejando falhar.`,
	`Pessoas quietas têm as mentes mais barulhentas.`,
	`Planejamento de longo prazo não lida com decisões futuras, mas com um futuro de decisões presentes.`,
	`Por mais brilhante que a estratégia seja, você deve sempre olhar para os resultados.`,
	`Por trás de toda empresa de sucesso existe uma estratégia.`,
	`Poucas coisas podem ajudar mais um indivíduo do que colocar a responsabilidade em cima dele, e deixa-lo saber que você confia nele.`,
	`Primeiro a chuva, depois o arco-íris. Se acostume, a ordem é sempre essa.`,
	`Primeiro, tenha um ideal prático e definitivo; uma meta, um objetivo. Segundo, disponha dos meios necessários para atingir os seus fins; sabedoria, dinheiro, materiais e métodos. Terceiro, ajuste todos os seus meios para esse fim.`,
	`Qualidade deveria ser como razão, que humanos têm por natureza, e animais irracionais não.`,
	`Quando a porta da felicidade se fecha, outra se abre, mas muitas vezes olhamos tanto tempo para a porta fechada que não vemos que outra foi aberta para nós.`,
	`Quando algo de bom acontece na sua vida, você começa a ligar os pontos. O que ficou para trás, tinha que ter ficado.`,
	`Quando alguém tem força para vencer a si mesmo, nasceu para grandes empreendimentos.`,
	`Quando alimentamos mais a nossa coragem do que os nossos medos, passamos a derrubar muros e a construir pontes.`,
	`Quando era jovem, descobri que nove de cada dez coisas que eu fazia eram um fracasso. Eu não queria ser um fracasso. Então, passei a trabalhar dez vezes mais.`,
	`Quando escrita em chinês, a palavra crise é composta de dois caracteres. Um representa o perigo e o outro representa a oportunidade. `,
	`Quando esticamos um pouco mais o sorriso, os problemas encolhem.`,
	`Quando estou formando uma equipe, eu sempre procuro primeiro pessoas que amam vencer. Se não consigo, então procuro aquelas que detestam perder.`,
	`Quando eu deixar de ser o que sou, eu irei me tornar o que poderia ser.`,
	`Quando eu fui para a escola, eles me perguntaram o que eu queria ser quando crescesse. Eu escrevi "feliz". Eles me disseram que eu não entendi a tarefa, e eu disse a eles que eles não entendiam a vida.`,
	`Quando mais duro eu trabalho, mais sortudo me torno. Quando você sentir o impulso, jogue com ele.`,
	`Quando todos pensam igual é porque ninguém está pensando.`,
	`Quando tudo parece estar indo contra você, lembre-se que o avião decola contra o vento, não a favor dele.`,
	`Quando você acredita em algo, acredite até o fim. Não dê margem para nenhum tipo de dúvida.`,
	`Quando você examina um problema e acha que ele é simples, você não se deu conta de quão complexo ele é.`,
	`Quando você perceber que identificou uma paixão, invista em si mesmo, descubra o que você precisa saber, que tipo de experiência e conhecimento você precisa desenvolver para fazer as coisas que você sente.`,
	`Quando você tem uma meta, o que era um obstáculo passa a ser uma etapa de um de nossos planos.`,
	`Quando você vive a vida com padrões pobres, você inflige dano a todos os que cruzam o seu caminho, especialmente aqueles que você ama.`,
	`Quando você vê um negócio bem-sucedido é porque alguém, algum dia, tomou uma decisão corajosa.`,
	`Quando é necessário mudar? Antes que seja necessário.`,
	`Quanto maior o artista, maior a dúvida.`,
	`Quanto mais difícil fica, mais próximo está o sucesso.`,
	`Quanto mais luxuoso o refeitório, mais ineficiente a empresa.`,
	`Quanto mais você aprende, mais você ganha.`,
	`Que ninguém se engane, só se consegue a simplicidade através de muito trabalho.`,
	`Quem decide pode errar. Quem não decide já errou.`,
	`Quem deseja vencer à custa de recomendações, sofre cruéis desilusões.`,
	`Quem nada empreender, nada terminará.`,
	`Quem nunca altera a sua opinião é como a água parada e começa a criar répteis no espírito.`,
	`Quem quiser alcançar um objetivo distante tem que dar muitos passos curtos.`,
	`Quer conquistar algo? Conquiste calos nas mãos e esfole os joelhos.`,
	`Quer você acredite que consiga fazer uma coisa ou não, você está certo.`,
	`Querer fazer tudo para todos é o primeiro passo para não fazer nada a ninguém.`,
	`Querer vencer significa já ter percorrido metade do caminho da vitória.`,
	`Quinze anos atrás as empresas competiam em preço. Hoje é qualidade. Amanhã será no design.`,
	`Reaja com inteligência mesmo quando for tratado com ignorância.`,
	`Resultados são obtidos aproveitando oportunidades e não resolvendo problemas.`,
	`Saber e não fazer ainda não é saber.`,
	`Saber esperar também é importante, por isso semeie aos poucos o sucesso de amanhã.`,
	`Saber esperar é uma virtude. Aceitar, sem questionar, que cada coisa tem um tempo certo para acontecer, é ter fé!`,
	`Saber não é suficiente; devemos aplicar. Estar disposto não é o suficiente; devemos fazer.`,
	`Saber não é suficiente; devemos aplicar.`,
	`Se A é o sucesso, então A é igual a X mais Y mais Z. O trabalho é X; Y é o lazer; e Z é manter a boca fechada.`,
	`Se caíres sete vezes, levanta-te oito.`,
	`Se nossa motivação fosse o dinheiro, nós teríamos vendido a companhia há muito tempo e estaríamos em uma praia.`,
	`Se não fosse pelo último minuto, muita coisa seria deixada de fazer.`,
	`Se não puder destacar-se pelo talento, vença pelo esforço.`,
	`Se não puder voar, corra. Se não puder correr, ande. Se não puder andar, rasteje, mas continue em frente de qualquer jeito.`,
	`Se o destino não te dá mais uma chance não desista, lute pelo que é seu.`,
	`Se o dinheiro for a sua esperança de independência, você jamais a terá. A única segurança verdadeira consiste numa reserva de sabedoria, de experiência e de competência.`,
	`Se os ventos não vão servir, leve os remos.`,
	`Se quer ver algo feito, peça a alguém que não tenha tempo; e para algo que não ficará feito, peça a alguém com tempo. A primeira pessoa não tem tempo porque faz tudo que lhe dizem; a segunda tem tempo porque não faz nada do que lhe pedem.`,
	`Se queres ser feliz amanhã, tenta hoje mesmo.`,
	`Se somos um peixe maior que o tanque em que fomos criados, ao invés de nos adaptarmos a ele, devíamos buscar o oceano.`,
	`Se sonhar grande dá o mesmo trabalho de sonhar pequeno, por que vou sonhar pequeno?`,
	`Se todo o ano fosse de férias alegres, divertirmo-nos tornar-se-ia mais aborrecido do que trabalhar.`,
	`Se um homem não sabe a que porto se dirige, nenhum vento lhe será favorável.`,
	`Se você acha a educação cara, experimente a ignorância.`,
	`Se você cansar, aprenda a descansar e não desistir.`,
	`Se você deseja que seus filhos acabem bem, gaste o dobro de tempo com eles, e metade do dinheiro.`,
	`Se você diz, eu posso ou eu não posso, você está certo de qualquer maneira.`,
	`Se você dá às pessoas um bom e suficiente "porquê", eles sempre descobrirão o "como".`,
	`Se você está atravessando um inferno, continue atravessando.`,
	`Se você está tentando persuadir as pessoas a fazerem algo, ou a comprarem algo, parece-me que você deveria usar a linguagem delas, a linguagem na qual elas pensam.`,
	`Se você for diferente, você se destacará.`,
	`Se você for realmente relevante para seu público, ele prestará atenção em você.`,
	`Se você não está disposto a arriscar, esteja disposto a uma vida comum.`,
	`Se você não pega a onda de mudança, você vai sucumbir debaixo dela.`,
	`Se você não pode explicar algo de forma simples, então você não entendeu muito bem o que tem a dizer.`,
	`Se você não sabe para onde está indo, qualquer lugar serve.`,
	`Se você não tentar, nunca vai saber se vai dar certo ou não.`,
	`Se você não traçou um plano para você mesmo, é possível que você caia no plano de outra pessoa. E adivinha o que ele planejou para você? Não muito.`,
	`Se você ouve uma voz dentro de você dizendo ‘você não pode fazer’, então faça e essa voz será silenciada.`,
	`Se você pode olhar para o que tem na vida, você sempre vai ter mais. Se você olhar para o que não tem, nunca terá o suficiente.`,
	`Se você quer algo novo, você precisa parar de fazer algo velho`,
	`Se você quer construir um negócio, construa primeiro as pessoas.`,
	`Se você quer entender como um leão ruge, não vá ao zoológico. Vá à selva.`,
	`Se você quer os acertos, esteja preparado para os erros.`,
	`Se você quer uma mudança permanente, pare de focar no tamanho de seus problemas e comece a focar no seu tamanho!`,
	`Se você quiser persuadir, fale de interesses em vez de apelar à razão.`,
	`Se você quiser se levantar, levante outra pessoa.`,
	`Se você realmente quer algo, não espere. Ensine você mesmo a ser impaciente.`,
	`Se você traçar metas absurdamente altas e falhar, seu fracasso será muito melhor que o sucesso de todos.`,
	`Se, em princípio, a ideia não é absurda, então não há esperança para ela.`,
	`Segure em quem te põe de pé, não em quem te puxa para baixo.`,
	`Seja dono do seu silêncio para não ser escravo das suas palavras.`,
	`Seja inteligente, mas nunca mostre demais.`,
	`Seja o que a sua mente pode conceber e acreditar, ela pode conseguir.`,
	`Seja uma medida de qualidade. Algumas pessoas não estão acostumadas a um ambiente onde se espera excelência.`,
	`Sem ação, as melhores intenções do mundo são nada mais do que isso: intenções.`,
	`Sempre que um homem passa a ambicionar cargos elevados, sua conduta começa a corromper-se.`,
	`Sempre que um homem supera os reveses, torna-se mental e espiritualmente mais forte.`,
	`Sempre que você se encontrar do lado da maioria, é hora de parar e refletir.`,
	`Sempre que você vir uma pessoa de sucesso, você sempre verá as glórias, nunca os sacrifícios que os levaram até ali.`,
	`Ser líder é como ser uma dama: se você precisa provar que é, então você não é.`,
	`Ser o homem mais rico no cemitério não importa para mim... ir para a cama à noite dizendo que fizemos algo maravilhoso, isso é o que realmente importa.`,
	`Seu tempo é limitado, então não o gaste vivendo a vida de outra pessoa.`,
	`Seus clientes mais insatisfeitos são a sua maior fonte de aprendizado.`,
	`Solucionar grandes problemas é mais fácil do que solucionar pequenos problemas.`,
	`Somente aqueles que aprendem a ver mais longe enxergam as melhores oportunidades.`,
	`Sonhar, afinal, é uma forma de planejamento.`,
	`Sonhe grande e se atreva a falhar.`,
	`Sorria. O sorriso ajuda-nos a descobrir motivos de alegria em volta de nós. Nossa alegria contagia os outros e a vida fica melhor.`,
	`Sorte é o que acontece quando a preparação encontra a oportunidade.`,
	`Sua tarefa é descobrir o seu trabalho e, então, com todo o coração, dedicar-se a ele.`,
	`Sucesso parece ser em grande parte uma questão de continuar depois que outros desistiram.`,
	`Sucesso é conseguir o que você quer; felicidade é gostar do que você conseguiu.`,
	`Sucesso é feito de 99% de fracasso.`,
	`Sucesso é um péssimo professor. Ele seduz as pessoas espertas para que pensem que não podem perder.`,
	`Sucesso? Eu não sei o que isso significa. Eu sou feliz. A definição de sucesso varia de pessoa para pessoa. Para mim, sucesso é paz anterior.`,
	`Superar o fácil não tem mérito, é obrigação; vencer o difícil é glorificante; ultrapassar o outrora impossível é esplendoroso.`,
	`São as pessoas que fazem as estratégias empresariais tomarem forma e se realizarem.`,
	`Só 80% do sucesso aparece.`,
	`Só evite fazer algo hoje se você quiser morrer e deixar assuntos inacabados.`,
	`Só trabalha no sentido duro da palavra, quem não gosta do que faz, por isso, eu, graças a Deus, nunca precisei trabalhar.`,
	`Só uma coisa torna um sonho impossível: o medo de fracassar.`,
	`Tarefa do gestor não é olhar como a empresa está, mas como ela deveria estar.`,
	`Tartarugas conhecem as estradas melhor do que os coelhos.`,
	`Tem dia que põe vírgula, tem dia que põe reticências, tem dia que põe ponto final e tem dia que tem a necessidade de virar a página.`,
	`Tem que existir este pioneiro, o indivíduo que tem a coragem, a ambição de superar os obstáculos que sempre se desenvolvem quando se tenta fazer algo de valor, especialmente quando é novo e diferente.`,
	`Tempo de decisão poupado, é tempo de ação ganho.`,
	`Tempos loucos exigem idéias loucas.`,
	`Tenha a noção exata de sua própria vida, ao invés de ter noção da vida dos outros.`,
	`Tenha até pesadelos, se necessário for. Mas sonhe.`,
	`Tenha em mente que o seu desejo em atingir o sucesso é mais importante que qualquer coisa.`,
	`Tenho aprendido ao longo dos anos que, quando a mente está pronta, isso diminui o medo.`,
	`Tenho reparado que mesmo aqueles que afirmam que tudo está predestinado e que não podemos mudar nada a respeito disso continuam olhando para os dois lados antes de atravessar a rua.`,
	`Tentar e falhar é, pelo menos, aprender. Não chegar a tentar é sofrer a inestimável perda do que poderia ter sido.`,
	`Tente mover o mundo. O primeiro passo será mover a si mesmo.`,
	`Tente não se tornar um homem de sucesso, mas sim tente tornarse um homem de valor.`,
	`Ter a noção exata de nossas próprias vidas, ao invés de ter noção da vida dos outros.`,
	`Ter sucesso não é apenas ter dinheiro, mas sim saber que uma ideia que parece impossível pode vir a quebrar paradigmas.`,
	`Ter sucesso é falhar repetidamente, mas sem perder o entusiasmo.`,
	`Toda a arte de ensinar é apenas a arte de acordar a curiosidade natural nas mentes jovens, com o propósito de serem satisfeitas mais tarde.`,
	`Toda a história da Ciência tem sido a percepção gradual de que eventos não acontecem de uma maneira arbitrária, mas que refletem uma ordem básica, que pode ou não ser divinamente inspirada.`,
	`Toda ação humana, quer se torne positiva ou negativa, precisa depender de motivação.`,
	`Toda ação implica riscos e custos. Mas eles são muitos menores do que os riscos e custos de uma confortável falta de ação.`,
	`Toda glória deriva da ousadia para começar.`,
	`Toda mente é um cofre. Não existem mentes impenetráveis, apenas chaves erradas.`,
	`Todas as coisas são difíceis antes de se tornarem fáceis.`,
	`Todo mundo tem uma ideia. Mas é verdadeiramente sobre executar a ideia e atrair outras pessoas para te ajudar a trabalhar na ideia.`,
	`Todo progresso acontece fora da zona de conforto.`,
	`Todos nós devemos ser coerentes com nosso próprio discurso.`,
	`Todos os seus sonhos podem se tornar realidade se você tem coragem para persegui-los.`,
	`Trabalhe, trabalhe, trabalhe; mas não se esqueça: vírgulas significam pausas.`,
	`Trate as pessoas da forma como elas devem ser e ajude-as a se tornarem o que elas são capazes de ser.`,
	`Triste não é mudar de ideia. Triste é não ter ideias para mudar.`,
	`Troque o "não" pelo "por que não"?`,
	`Troque suas folhas, mas não perca suas raízes. Mude suas opiniões, mas não perca seus princípios.`,
	`Tudo o que você sempre quis está do outro ado do seu medo.`,
	`Tudo que você pode fazer, ou sonha que pode, comece. Ousadia tem genialidade, poder e magia.`,
	`Tudo tem beleza. Mas nem todos podem ver.`,
	`Tudo é uma questão de ponto de vista: pra formiga, gota de chuva é tsunami.`,
	`Um adulto médio tem entre 40 e 60 mil pensamentos por dia.`,
	`Um diamante é um pedaço de carvão que se saiu bem sob pressão.`,
	`Um dos segredos do sucesso é se recusar a deixar que adversidades temporárias nos derrotem.`,
	`Um homem com coragem faz uma maioria.`,
	`Um homem de sucesso é aquele que cria uma parede com os tijolos que jogaram nele.`,
	`Um líder não é alguém a quem foi dada uma coroa, mas quem foi dada a responsabilidade fazer sobressair o melhor que há nos outros.`,
	`Um líder é um vendedor de esperança.`,
	`Um profissional é aquele que faz o seu melhor trabalho quando menos vontade tem de o fazer.`,
	`Uma boa comunicação é 51% do negócio`,
	`Uma chave importante para o sucesso é a autoconfiança. Uma chave importante para a autoconfiança é a preparação.`,
	`Uma ideia é um feito de associação.`,
	`Uma longa viagem começa com um único passo.`,
	`Uma marca para uma empresa é como a reputação para uma pessoa. Você ganha reputação ao tentar fazer bem coisas difíceis.`,
	`Uma marca é simplesmente uma coleção de percepções na mente do consumidor.`,
	`Uma palavra grosseira, uma expressão bizarra, ensinou-me por vezes mais do que dez belas frases.`,
	`Uma pessoa imatura pensa que todas as suas escolhas geram ganhos. Uma pessoa madura sabe que todas as escolhas têm perdas. `,
	`Uma pessoa que nunca cometeu um erro, nunca tentou nada de novo.`,
	`Uma vida não examinada, não vale a pena ser vivida.`,
	`Unir-se é um bom começo, manter a união é um progresso, e trabalhar em conjunto é a vitória.`,
	`Vamos inventar o amanhã e parar de nos preocupar com o passado. `,
	`Veja o lado bom das coisas. Você já parou pra pensar o que seriam das oportunidades se não fossem as mudanças?`,
	`Vencer é ter a esperança sempre renovada, lembrando que o sol nasce todos os dias e para todos.`,
	`Vencer é ter um sentimento profundo de fé, força e perseverança mesmo em momentos difíceis.`,
	`Vencer ������, apesar de tudo que possa acontecer, acreditar nas pessoas e saber que por de traz de cada ato humano, por mais difícil que alguém possa parecer há sempre uma intenção positiva para consigo.`,
	`Viva a cada dia como se a vida estivesse começando.`,
	`Viva como se fosse morrer amanhã, aprenda como se fosse viver para sempre.`,
	`Você cresce mais forte no fracasso do que no sucesso.`,
	`Você deve lutar mais de uma batalha para se tornar um vencedor.`,
	`Você deve pensar grande e começar pequeno.`,
	`Você gostaria que eu lhe desse uma fórmula para o sucesso? É muito simples: dobre sua taxa de falhas.`,
	`Você nunca pode atravessar o oceano até que você tenha coragem de perder de vista a costa.`,
	`Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados.`,
	`Você não aprende a andar seguindo regras. Você aprende tentando e caindo.`,
	`Você não constrói nada sozinho. Você descobre o que as pessoas querem e então, constrói para elas.`,
	`Você não fica rico com o que ganha; fica rico com o que poupa`,
	`Você não pode deixar de usar a criatividade. Quanto mais você usa, mais você tem.`,
	`Você não pode vencer a quem não se rende.`,
	`Você não precisa ser perfeito no trabalho, mas deve encontrar três ou quatro coisas que sabe fazer melhor do que 1000 pessoas.`,
	`Você não tem como prever os obstáculos, mas a forma de encará-los é responsabilidade sua.`,
	`Você perde 100% dos tiros que não dá.`,
	`Você pode ensinar um peru a subir uma árvore, mas é mais fácil contratar um esquilo.`,
	`Você pode ficar desapontado se fracassar, mas estará condenado se não se arriscar.`,
	`Você pode sentar e analisar as coisas para sempre, mas enquanto você estiver fazendo isso, os concorrentes já terão seguido em frente.`,
	`Você pode ser desencorajado com os erros ou aprender com eles, então siga em frente e continue falhando. Erre o máximo que puder. É aí que você vai conseguir o sucesso.`,
	`Você precisa ver as coisas como elas são, não pior do que elas são, então, imagine-as melhor do que elas são, e transforme-as nessa forma.`,
	`Você será bem sucedido... Mesmo que os demais não acreditem. Basta que tenha confiança em si mesmo.`,
	`Você toma sua vida em suas próprias mãos e o que acontece? Uma coisa terrível, ninguém para colocar a culpa.`,
	`Você vê coisas e diz: "Por quê?". Mas eu sonho coisas que nunca existiram e digo: "Por que não?"`,
	`Você é totalmente perfeito e seu sucesso na vida será diretamente proporcional à sua habilidade de aceitar esta verdade sobre você mesmo.`,
	`Você é, ao mesmo tempo, o maior fator de sucesso e o maior freio de mão.`,
	`Vá até onde a sua vista alcançar e, ao chegar lá, você conseguirá enxergar mais longe.`,
	`Vá na direção de seus sonhos. Viva a vida que você imaginou.`,
	`Às vezes para ensinar algo bom, é preciso ser um pouco rude.`,
	`Águas mansas não fazem bons marinheiros.`,
	`É absolutamente impossível que um homem alcance fama e fortuna sem levar outros consigo.`,
	`É fazendo que se aprende, aquilo que se deve aprender a fazer.`,
	`É fácil fazer dinheiro, difícil é fazer a diferença.`,
	`É fácil ter princípios quando se é rico. O valor está em ter princípios quando se é pobre.`,
	`É impossível avaliar a força que possuímos sem medir o tamanho do obstáculo que podemos vencer, nem o valor de uma ação sem sabermos o sacrifício que ela comporta.`,
	`É impossível avaliar a força que possuímos sem medir o tamanho do obstáculo que podemos vencer.`,
	`É impossível avaliar o valor de uma ação sem sabermos o sacrifício que ela comporta.`,
	`É mais fácil obter o sucesso do que mantê-lo.`,
	`É mais fácil ser o primeiro do que continuar a ser o primeiro.`,
	`É mais importante adotar a estratégia correta do que buscar o sucesso imediato.`,
	`É melhor estar preparado para uma oportunidade e não ter nenhuma do que ter uma oportunidade e não estar preparado.`,
	`É melhor ser rejeitado por ser sincero do que ser aceito sendo hipócrita.`,
	`É muito comum que as pessoas estejam trabalhando duro na coisa errada. Trabalhar na coisa certa é provavelmente mais importante do que trabalhar duro.`,
	`É o seu lugar no mundo; é a sua vida. Vá em frente e faça tudo o que puder com ela, e torne-a a vida que você quer viver.`,
}
